SELECT ttk.MADOT, ttk.SHS,ttk.SOHOSO,kh.HOSOCHA,
	HOTEN, kh.DIENTHOAI,( SONHA +'  '+DUONG+',  P.'+ p.TENPHUONG+',  Q.'+q.TENQUAN) as 'DIACHI',
	lkh.TENLOAI as 'LOAIKH',lhs.TENLOAI as 'LOAIHS', CONVERT(VARCHAR(20),kh.NGAYNHAN,103) AS 'NGAYNHAN', 
	CONVERT(VARCHAR(20),ttk.NGAYNHAN,103) AS 'NGAYGIAOTTK', FULLNAME, ttk.NGAYTKGD, ttk.NGAYTRAHS
FROM TOTHIETKE ttk, DON_KHACHHANG kh,QUAN q,PHUONG p
	, LOAI_HOSO lhs, USERS us, LOAI_KHACHHANG lkh 
 WHERE kh.LOAIKH=lkh.MALOAI AND  kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN 
		AND kh.PHUONG=p.MAPHUONG AND lhs.MALOAI=kh.LOAIHOSO 
		AND ttk.SOHOSO=kh.SOHOSO AND us.USERNAME=ttk.SODOVIEN
		AND ( SONHA +'  '+DUONG+',  P.'+ p.TENPHUONG+',  Q.'+q.TENQUAN) LIKE N'%bình long%'