UPDATE DANHMUCVATTU SET CREATEDATE='1/1/2011' WHERE NHOMVT='XDCB'
UPDATE DANHMUCVATTU SET CREATEDATE='12/12/2011' WHERE NHOMVT !='XDCB'

CREATE TABLE BOVATTAOSAN
(
	MABOVT VARCHAR(250) PRIMARY KEY NOT NULL,
	TENBOVT NVARCHAR(MAX),
	CREATEBY VARCHAR(50),
	CREATEDATE DATETIME,
	MODIFYBY VARCHAR(20),
	MODIFYDATE DATETIME
)
GO

CREATE TABLE CHITIETBOVATTAOSAN
(
	STT INT IDENTITY (1,1) PRIMARY KEY,
	MAHIEU VARCHAR(20),
	TENVT NVARCHAR(250), 
	DVT NVARCHAR(20),
	NHOM NVARCHAR(20),
	LOAISN VARCHAR(20),
	KHOILUONG FLOAT, 
	CHON BIT,
	MABOVT VARCHAR(250),
	CREATEBY VARCHAR(50),
	CREATEDATE DATETIME,
	MODIFYBY VARCHAR(20),
	MODIFYDATE DATETIME,
	CONSTRAINT FR_VTTS FOREIGN KEY (MABOVT) REFERENCES BOVATTAOSAN(MABOVT)
)
GO

CREATE TABLE BGDC_CONGTACBANGIA
(
	STT INT IDENTITY (1,1) PRIMARY KEY,
	SOLAN INT,
	SHS VARCHAR(50),
	MAHIEU VARCHAR(20),
	MAHDG VARCHAR(20),
	TENVT NVARCHAR(250), 
	DVT NVARCHAR(20),
	NHOM NVARCHAR(20),
	LOAISN VARCHAR(20),
	KHOILUONG FLOAT,
	DONGIAVL FLOAT,
	DONGIANC FLOAT,
	DONGIAMTC FLOAT,
	GHICHU NVARCHAR(250),
	CREATEBY VARCHAR(50),
	CREATEDATE DATETIME,
	MODIFYBY VARCHAR(20),
	MODIFYDATE DATETIME,
	CONSTRAINT FR_CTBGDC_SHS FOREIGN KEY (SHS) REFERENCES DON_KHACHHANG(SHS),
	CONSTRAINT FR_CTBGDC_VT FOREIGN KEY (MAHIEU) REFERENCES DANHMUCVATTU(MAHIEU)	
)
GO

CREATE TABLE BGDC_KHOILUONGXDCB
(
	STT INT IDENTITY(1,1) PRIMARY KEY,
	SOLAN INT,
	SHS VARCHAR(50) NOT NULL,
	CATNHUA FLOAT,
	BOCNHUA FLOAT,
	CATBTXM FLOAT,
	BOCBTXM FLOAT,
	DATCAP4 FLOAT,
	DATCAP3 FLOAT,
	CAT		FLOAT,
	DA04	FLOAT,
	XUCDAT	FLOAT,
	CPVATTU	FLOAT,
	CPNHANCONG FLOAT,
	CPMAYTHICONG FLOAT,
	CPCABA	FLOAT,
	CHIPHITRUCTIEP FLOAT,
	CHIPHICHUNG FLOAT,	
	TAILAPMATDUONG FLOAT,
	TLMDTRUOCTHUE FLOAT,
	CPGAN FLOAT DEFAULT 0,
	CPNHUA FLOAT DEFAULT 0,
	CONG1 FLOAT,
	THUE55 FLOAT,
	CONG3 FLOAT,
	THUEGTGT FLOAT,
	TONGIATRI FLOAT,
	GHICHU NVARCHAR(250),
	PHICABA BIT DEFAULT 0,
	PHIGIAMSAT BIT DEFAULT 1,
	PHIQUANLY BIT DEFAULT 1,
	CREATEBY VARCHAR(50),
	CREATEDATE DATETIME,
	MODIFYBY VARCHAR(20),
	MODIFYDATE DATETIME,
	BGLOG NVARCHAR(MAX),
	CONSTRAINT FR_KLXDVBDC_SHS FOREIGN KEY (SHS) REFERENCES DON_KHACHHANG(SHS)
)
GO

CREATE TABLE BGDC_KICHTHUOCPHUIDAO
(
	STT INT IDENTITY(1,1) PRIMARY KEY,
	SOLAN INT,
	SHS VARCHAR(50) NOT NULL,
	MADANHMUC VARCHAR(20) NOT NULL,
	TENKETCAU NVARCHAR(MAX),
	DVT NVARCHAR(20),
	DAI FLOAT,
	RONG FLOAT,
	DOSAU FLOAT,
	SOLUONG FLOAT,
	KHOILUONG FLOAT,
	CHUVI FLOAT,
	THETICH FLOAT,
	COTINHTL BIT,
	GHICHU NVARCHAR(250),
	CREATEBY VARCHAR(50),
	CREATEDATE DATETIME,
	MODIFYBY VARCHAR(20),
	MODIFYDATE DATETIME,
	CONSTRAINT FR_KTPDDC_SHS FOREIGN KEY (SHS) REFERENCES DON_KHACHHANG(SHS),
	CONSTRAINT FR_KTPDDC_VT FOREIGN KEY (MADANHMUC) REFERENCES DANHMUCTAILAPMATDUONG(MADANHMUC)	
)
GO