DROP PROCEDURE TONGKETCHIPHI
GO

CREATE PROCEDURE TONGKETCHIPHI
	@SHS VARCHAR(50),
	@A FLOAT OUTPUT,
	@B FLOAT OUTPUT,
	@C FLOAT OUTPUT,
	@CPCABA FLOAT OUTPUT,	
	@TOTAL FLOAT OUTPUT,
	@VAT FLOAT OUTPUT,
	@B1 FLOAT OUTPUT,
	@C1 FLOAT OUTPUT,
	@C2 FLOAT OUTPUT,
	@D FLOAT OUTPUT,
	@E	FLOAT OUTPUT,
	@F FLOAT OUTPUT,
	@G FLOAT OUTPUT,
	@H FLOAT OUTPUT,
	@I FLOAT OUTPUT,
	@J FLOAT OUTPUT,
	@K FLOAT OUTPUT,
	@L FLOAT OUTPUT
AS
	SELECT @A= SUM(KHOILUONG*DONGIAVL) FROM BG_CONGTACBANGIA WHERE LOAISN <> 'SDL'
	SELECT @B= SUM(KHOILUONG*DONGIANC) FROM BG_CONGTACBANGIA WHERE LOAISN <> 'SDL'
	SELECT @C= SUM(KHOILUONG*DONGIAMTC) FROM BG_CONGTACBANGIA WHERE LOAISN <> 'SDL'
	SET @CPCABA=0
	SET @B1= @B*2.80
	SET @C1= @C*1.34
	SET @C2= 0.02*(@A+@B1+@C1)
	SET @D= @A + @B1 + @C1 + @C2
	SET @E= 0.05*@D
	SET @F= @D+@E
	SET @G= 0.055*@F
	SET @H= @F+@G
	SET @I= 0.0207*1.3*@H
	SET @J= 0.01964*@H
	SET @K= 0.02125*@H
	SET @L= @H+@J+@I+@K
	SET @VAT= 0.1*@L
	SET @TOTAL= @L+@VAT
	
	