DROP PROCEDURE TONGKETCHIPHI
GO

CREATE PROCEDURE TONGKETCHIPHI
	@SHS VARCHAR(50),
	@A FLOAT OUTPUT,
	@B FLOAT OUTPUT,
	@C FLOAT OUTPUT,
	@CPCABA FLOAT OUTPUT,	
	@TOTAL FLOAT OUTPUT,
	@VAT FLOAT OUTPUT,
	@B1 FLOAT OUTPUT,
	@C1 FLOAT OUTPUT,
	@C2 FLOAT OUTPUT,
	@D FLOAT OUTPUT,
	@E	FLOAT OUTPUT,
	@F FLOAT OUTPUT,
	@G FLOAT OUTPUT,
	@H FLOAT OUTPUT,
	@I FLOAT OUTPUT,
	@J FLOAT OUTPUT,
	@K FLOAT OUTPUT,
	@L FLOAT OUTPUT
AS
	DECLARE @NC FLOAT
	DECLARE @MTC FLOAT
	DECLARE @CA3 FLOAT
	DECLARE @PHIKHAC FLOAT
	DECLARE @PHICHUNG FLOAT
	DECLARE @TRUOCTHUE FLOAT
	DECLARE @PHIKSTK FLOAT
	DECLARE @HSKSTK FLOAT
	DECLARE @PHIGIAMSAT FLOAT
	DECLARE @CHIPHIQL FLOAT
	DECLARE @THUEVAT FLOAT
	SELECT @NC=NC,@MTC=MTC,@CA3=CABA/100,@PHIKHAC=PHIKHAC/100,@PHICHUNG=PHICHUNG/100,@TRUOCTHUE=TRUOCTHUE/100, @PHIKSTK=PHIKSTK/100,@HSKSTK=HSKSTK
			,@PHIGIAMSAT=PHIGIAMSAT/100,@CHIPHIQL=CHIPHIQL/100,@THUEVAT=VAT/100 FROM BG_HESOKINHPHI WHERE CHON='True'
	SELECT @A= SUM(KHOILUONG*DONGIAVL) FROM BG_CONGTACBANGIA WHERE LOAISN = 'CM'
	SELECT @B= SUM(KHOILUONG*DONGIANC) FROM BG_CONGTACBANGIA WHERE LOAISN <> 'CMTH'
	SELECT @C= SUM(KHOILUONG*DONGIAMTC) FROM BG_CONGTACBANGIA WHERE LOAISN <> 'CMTH'
	SET @B1= @B*@NC
	SET @C1= @C*@MTC
	SET @CPCABA= @CA3*@B1
	SET @C2= @PHIKHAC*(@A+@B1+@C1)
	SET @D= @A + @B1 + @C1 + @C2
	SET @E= @PHICHUNG*@D
	SET @F= @D+@E
	SET @G= @TRUOCTHUE*@F
	SET @H= @F+@G
	SET @I= @PHIKSTK*@HSKSTK*@H
	SET @J= @PHIGIAMSAT*@H
	SET @K= @CHIPHIQL*@H
	SET @L= @H+@J+@I+@K
	SET @VAT= @THUEVAT*@L
	SET @TOTAL= @L+@VAT
	
	