/* VIEW */
CREATE VIEW V_DONKHACHHANG
AS
	SELECT kh.* ,q.MAQUAN,  UPPER(q.TENQUAN) AS 'TENQUAN' , p.MAPHUONG, p.TENPHUONG, UPPER(result.TENLOAI) AS 'TENLOAI',USERNAME, UPPER(FULLNAME) as 'NGUOILAP'
	FROM   USERS,DON_KHACHHANG kh,QUAN q,PHUONG p, LOAI_KHACHHANG lkh, (SELECT MADOT,loai.TENLOAI FROM  DOT_NHAN_DON dot, LOAI_HOSO loai WHERE loai.MALOAI = dot.LOAIDON ) as result
	WHERE  kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND lkh.MALOAI=kh.LOAIKH AND  kh.MADOT=result.MADOT 


/* SP AND USERNAME='admin'  */
CREATE VIEW V_CHUYENDON
AS
	SELECT ttk.MADOT as 'TTKMD',ttk.SOHOSO as 'TTKSOHOSO', kh.* ,q.MAQUAN,  UPPER(q.TENQUAN) AS 'TENQUAN' , p.MAPHUONG, p.TENPHUONG, UPPER(result.TENLOAI) AS 'TENLOAI',USERNAME, UPPER(FULLNAME) as 'NGUOILAP'
	FROM   TOTHIETKE ttk,USERS,DON_KHACHHANG kh,QUAN q,PHUONG p, LOAI_KHACHHANG lkh, (SELECT MADOT,loai.TENLOAI FROM  DOT_NHAN_DON dot, LOAI_HOSO loai WHERE loai.MALOAI = dot.LOAIDON ) as result
	WHERE  ttk.SOHOSO=kh.SOHOSO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND lkh.MALOAI=kh.LOAIKH AND  kh.MADOT=result.MADOT 

/* SP AND VIEW */

CREATE VIEW V_DANHSACH_HS_SDV
AS
	SELECT ttk.MADOT,ttk.SHS,HOTEN,kh.DIENTHOAI,(SONHA +' '+ DUONG +', P.'+p.TENPHUONG+', Q.'+ q.TENQUAN ) as 'DIACHI', NGAYNHAN= CONVERT(VARCHAR(10),ttk.NGAYNHAN,103), lhs.TENLOAI, kh.PHUONG, kh.QUAN, DUONG, SONHA,SODOVIEN, FULLNAME  
    FROM TOTHIETKE ttk, DON_KHACHHANG kh,QUAN q,PHUONG p, LOAI_HOSO lhs, USERS us
    WHERE  kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND lhs.MALOAI=kh.LOAIHOSO AND ttk.SOHOSO=kh.SOHOSO AND us.USERNAME=ttk.SODOVIEN

SELECT * FROM V_DANHSACH_HS_SDV  WHERE SODOVIEN='chanhthang' AND NGAYNHAN ='25/08/2011' ORDER BY QUAN,PHUONG,DUONG,SONHA DESC