SELECT MADOT, NGAYLAPDON, TENLOAI, 
	CASE WHEN CHUYENDON = '' THEN  'CHUYEN 1 PHAN' WHEN CHUYENDON='True' THEN '123' ELSE '456' END as 'ten tang'
FROM DOT_NHAN_DON dot, LOAI_HOSO loai
WHERE loai.MALOAI = dot.LOAIDON
ORDER BY NGAYLAPDON DESC

SELECT DISTINCT  SOHOSO,HOTEN, (SONHA +' '+ DUONG +', '+p.TENPHUONG+', '+ q.TENQUAN ) as 'DIACHI',NGAYNHAN, lkh.TENLOAI
FROM DON_KHACHHANG kh,QUAN q,PHUONG p, LOAI_KHACHHANG lkh
WHERE  kh.QUAN = q.MAQUAN AND  kh.PHUONG = p.MAPHUONG AND kh.LOAIKH=lkh.MALOAI