#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanHoaWater.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAPNUOCTANHOA")]
	public partial class CapNuocTanHoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void UpdateTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void DeleteTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void InsertTB_GANMOI(TB_GANMOI instance);
    partial void UpdateTB_GANMOI(TB_GANMOI instance);
    partial void DeleteTB_GANMOI(TB_GANMOI instance);
    #endregion
		
		public CapNuocTanHoaDataContext() : 
				base(global::TanHoaWater.Properties.Settings.Default.CAPNUOCTANHOAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CapNuocTanHoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CapNuocTanHoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CapNuocTanHoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CapNuocTanHoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_DULIEUKHACHHANG> TB_DULIEUKHACHHANGs
		{
			get
			{
				return this.GetTable<TB_DULIEUKHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<TB_GANMOI> TB_GANMOIs
		{
			get
			{
				return this.GetTable<TB_GANMOI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DULIEUKHACHHANG")]
	public partial class TB_DULIEUKHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KHU;
		
		private string _DOT;
		
		private string _CUON_GCS;
		
		private string _CUON_STT;
		
		private string _LOTRINH;
		
		private string _DANHBO;
		
		private string _NGAYGANDH;
		
		private string _HOPDONG;
		
		private string _HOTEN;
		
		private string _SONHA;
		
		private string _TENDUONG;
		
		private string _PHUONG;
		
		private string _QUAN;
		
		private string _CHUKY;
		
		private string _CODE;
		
		private string _CODEFU;
		
		private string _GIABIEU;
		
		private string _DINHMUC;
		
		private string _SH;
		
		private string _HCSN;
		
		private string _SX;
		
		private string _DV;
		
		private string _CODH;
		
		private string _HIEUDH;
		
		private string _SOTHANDH;
		
		private string _CAP;
		
		private string _CHITHAN;
		
		private string _CHIGOC;
		
		private string _VITRIDHN;
		
		private string _SODHN;
		
		private System.Nullable<System.DateTime> _NGAYTHAY;
		
		private System.Nullable<System.DateTime> _NGAYKIEMDINH;
		
		private string _MSTHUE;
		
		private string _SOHO;
		
		private string _CHISOKYTRUOC;
		
		private System.Nullable<bool> _BAOTHAY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYBY;
		
		private System.Nullable<int> _KY;
		
		private System.Nullable<int> _NAM;
		
		private string _DIENTHOAI;
		
		private System.Nullable<int> _KY_;
		
		private string _MADMA;
		
		private System.Nullable<int> _CHUKYDS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKHUChanging(string value);
    partial void OnKHUChanged();
    partial void OnDOTChanging(string value);
    partial void OnDOTChanged();
    partial void OnCUON_GCSChanging(string value);
    partial void OnCUON_GCSChanged();
    partial void OnCUON_STTChanging(string value);
    partial void OnCUON_STTChanged();
    partial void OnLOTRINHChanging(string value);
    partial void OnLOTRINHChanged();
    partial void OnDANHBOChanging(string value);
    partial void OnDANHBOChanged();
    partial void OnNGAYGANDHChanging(string value);
    partial void OnNGAYGANDHChanged();
    partial void OnHOPDONGChanging(string value);
    partial void OnHOPDONGChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSONHAChanging(string value);
    partial void OnSONHAChanged();
    partial void OnTENDUONGChanging(string value);
    partial void OnTENDUONGChanged();
    partial void OnPHUONGChanging(string value);
    partial void OnPHUONGChanged();
    partial void OnQUANChanging(string value);
    partial void OnQUANChanged();
    partial void OnCHUKYChanging(string value);
    partial void OnCHUKYChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnCODEFUChanging(string value);
    partial void OnCODEFUChanged();
    partial void OnGIABIEUChanging(string value);
    partial void OnGIABIEUChanged();
    partial void OnDINHMUCChanging(string value);
    partial void OnDINHMUCChanged();
    partial void OnSHChanging(string value);
    partial void OnSHChanged();
    partial void OnHCSNChanging(string value);
    partial void OnHCSNChanged();
    partial void OnSXChanging(string value);
    partial void OnSXChanged();
    partial void OnDVChanging(string value);
    partial void OnDVChanged();
    partial void OnCODHChanging(string value);
    partial void OnCODHChanged();
    partial void OnHIEUDHChanging(string value);
    partial void OnHIEUDHChanged();
    partial void OnSOTHANDHChanging(string value);
    partial void OnSOTHANDHChanged();
    partial void OnCAPChanging(string value);
    partial void OnCAPChanged();
    partial void OnCHITHANChanging(string value);
    partial void OnCHITHANChanged();
    partial void OnCHIGOCChanging(string value);
    partial void OnCHIGOCChanged();
    partial void OnVITRIDHNChanging(string value);
    partial void OnVITRIDHNChanged();
    partial void OnSODHNChanging(string value);
    partial void OnSODHNChanged();
    partial void OnNGAYTHAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHAYChanged();
    partial void OnNGAYKIEMDINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKIEMDINHChanged();
    partial void OnMSTHUEChanging(string value);
    partial void OnMSTHUEChanged();
    partial void OnSOHOChanging(string value);
    partial void OnSOHOChanged();
    partial void OnCHISOKYTRUOCChanging(string value);
    partial void OnCHISOKYTRUOCChanged();
    partial void OnBAOTHAYChanging(System.Nullable<bool> value);
    partial void OnBAOTHAYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnMODIFYDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFYDATEChanged();
    partial void OnMODIFYBYChanging(string value);
    partial void OnMODIFYBYChanged();
    partial void OnKYChanging(System.Nullable<int> value);
    partial void OnKYChanged();
    partial void OnNAMChanging(System.Nullable<int> value);
    partial void OnNAMChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnKY_Changing(System.Nullable<int> value);
    partial void OnKY_Changed();
    partial void OnMADMAChanging(string value);
    partial void OnMADMAChanged();
    partial void OnCHUKYDSChanging(System.Nullable<int> value);
    partial void OnCHUKYDSChanged();
    #endregion
		
		public TB_DULIEUKHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHU", DbType="VarChar(255)")]
		public string KHU
		{
			get
			{
				return this._KHU;
			}
			set
			{
				if ((this._KHU != value))
				{
					this.OnKHUChanging(value);
					this.SendPropertyChanging();
					this._KHU = value;
					this.SendPropertyChanged("KHU");
					this.OnKHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOT", DbType="VarChar(255)")]
		public string DOT
		{
			get
			{
				return this._DOT;
			}
			set
			{
				if ((this._DOT != value))
				{
					this.OnDOTChanging(value);
					this.SendPropertyChanging();
					this._DOT = value;
					this.SendPropertyChanged("DOT");
					this.OnDOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_GCS", DbType="NVarChar(MAX)")]
		public string CUON_GCS
		{
			get
			{
				return this._CUON_GCS;
			}
			set
			{
				if ((this._CUON_GCS != value))
				{
					this.OnCUON_GCSChanging(value);
					this.SendPropertyChanging();
					this._CUON_GCS = value;
					this.SendPropertyChanged("CUON_GCS");
					this.OnCUON_GCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_STT", DbType="NVarChar(MAX)")]
		public string CUON_STT
		{
			get
			{
				return this._CUON_STT;
			}
			set
			{
				if ((this._CUON_STT != value))
				{
					this.OnCUON_STTChanging(value);
					this.SendPropertyChanging();
					this._CUON_STT = value;
					this.SendPropertyChanged("CUON_STT");
					this.OnCUON_STTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOTRINH", DbType="NVarChar(100)")]
		public string LOTRINH
		{
			get
			{
				return this._LOTRINH;
			}
			set
			{
				if ((this._LOTRINH != value))
				{
					this.OnLOTRINHChanging(value);
					this.SendPropertyChanging();
					this._LOTRINH = value;
					this.SendPropertyChanged("LOTRINH");
					this.OnLOTRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBO", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DANHBO
		{
			get
			{
				return this._DANHBO;
			}
			set
			{
				if ((this._DANHBO != value))
				{
					this.OnDANHBOChanging(value);
					this.SendPropertyChanging();
					this._DANHBO = value;
					this.SendPropertyChanged("DANHBO");
					this.OnDANHBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGANDH", DbType="NVarChar(255)")]
		public string NGAYGANDH
		{
			get
			{
				return this._NGAYGANDH;
			}
			set
			{
				if ((this._NGAYGANDH != value))
				{
					this.OnNGAYGANDHChanging(value);
					this.SendPropertyChanging();
					this._NGAYGANDH = value;
					this.SendPropertyChanged("NGAYGANDH");
					this.OnNGAYGANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOPDONG", DbType="VarChar(255)")]
		public string HOPDONG
		{
			get
			{
				return this._HOPDONG;
			}
			set
			{
				if ((this._HOPDONG != value))
				{
					this.OnHOPDONGChanging(value);
					this.SendPropertyChanging();
					this._HOPDONG = value;
					this.SendPropertyChanged("HOPDONG");
					this.OnHOPDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(MAX)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONHA", DbType="NVarChar(MAX)")]
		public string SONHA
		{
			get
			{
				return this._SONHA;
			}
			set
			{
				if ((this._SONHA != value))
				{
					this.OnSONHAChanging(value);
					this.SendPropertyChanging();
					this._SONHA = value;
					this.SendPropertyChanged("SONHA");
					this.OnSONHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(MAX)")]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this.OnTENDUONGChanging(value);
					this.SendPropertyChanging();
					this._TENDUONG = value;
					this.SendPropertyChanged("TENDUONG");
					this.OnTENDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUONG", DbType="NVarChar(255)")]
		public string PHUONG
		{
			get
			{
				return this._PHUONG;
			}
			set
			{
				if ((this._PHUONG != value))
				{
					this.OnPHUONGChanging(value);
					this.SendPropertyChanging();
					this._PHUONG = value;
					this.SendPropertyChanged("PHUONG");
					this.OnPHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUAN", DbType="NVarChar(255)")]
		public string QUAN
		{
			get
			{
				return this._QUAN;
			}
			set
			{
				if ((this._QUAN != value))
				{
					this.OnQUANChanging(value);
					this.SendPropertyChanging();
					this._QUAN = value;
					this.SendPropertyChanged("QUAN");
					this.OnQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKY", DbType="NVarChar(255)")]
		public string CHUKY
		{
			get
			{
				return this._CHUKY;
			}
			set
			{
				if ((this._CHUKY != value))
				{
					this.OnCHUKYChanging(value);
					this.SendPropertyChanging();
					this._CHUKY = value;
					this.SendPropertyChanged("CHUKY");
					this.OnCHUKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEFU", DbType="NVarChar(255)")]
		public string CODEFU
		{
			get
			{
				return this._CODEFU;
			}
			set
			{
				if ((this._CODEFU != value))
				{
					this.OnCODEFUChanging(value);
					this.SendPropertyChanging();
					this._CODEFU = value;
					this.SendPropertyChanged("CODEFU");
					this.OnCODEFUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABIEU", DbType="NVarChar(255)")]
		public string GIABIEU
		{
			get
			{
				return this._GIABIEU;
			}
			set
			{
				if ((this._GIABIEU != value))
				{
					this.OnGIABIEUChanging(value);
					this.SendPropertyChanging();
					this._GIABIEU = value;
					this.SendPropertyChanged("GIABIEU");
					this.OnGIABIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DINHMUC", DbType="NVarChar(255)")]
		public string DINHMUC
		{
			get
			{
				return this._DINHMUC;
			}
			set
			{
				if ((this._DINHMUC != value))
				{
					this.OnDINHMUCChanging(value);
					this.SendPropertyChanging();
					this._DINHMUC = value;
					this.SendPropertyChanged("DINHMUC");
					this.OnDINHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH", DbType="NVarChar(255)")]
		public string SH
		{
			get
			{
				return this._SH;
			}
			set
			{
				if ((this._SH != value))
				{
					this.OnSHChanging(value);
					this.SendPropertyChanging();
					this._SH = value;
					this.SendPropertyChanged("SH");
					this.OnSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSN", DbType="NVarChar(255)")]
		public string HCSN
		{
			get
			{
				return this._HCSN;
			}
			set
			{
				if ((this._HCSN != value))
				{
					this.OnHCSNChanging(value);
					this.SendPropertyChanging();
					this._HCSN = value;
					this.SendPropertyChanged("HCSN");
					this.OnHCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SX", DbType="NVarChar(255)")]
		public string SX
		{
			get
			{
				return this._SX;
			}
			set
			{
				if ((this._SX != value))
				{
					this.OnSXChanging(value);
					this.SendPropertyChanging();
					this._SX = value;
					this.SendPropertyChanged("SX");
					this.OnSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="NVarChar(255)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this.OnDVChanging(value);
					this.SendPropertyChanging();
					this._DV = value;
					this.SendPropertyChanged("DV");
					this.OnDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODH", DbType="NVarChar(255)")]
		public string CODH
		{
			get
			{
				return this._CODH;
			}
			set
			{
				if ((this._CODH != value))
				{
					this.OnCODHChanging(value);
					this.SendPropertyChanging();
					this._CODH = value;
					this.SendPropertyChanged("CODH");
					this.OnCODHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEUDH", DbType="NVarChar(255)")]
		public string HIEUDH
		{
			get
			{
				return this._HIEUDH;
			}
			set
			{
				if ((this._HIEUDH != value))
				{
					this.OnHIEUDHChanging(value);
					this.SendPropertyChanging();
					this._HIEUDH = value;
					this.SendPropertyChanged("HIEUDH");
					this.OnHIEUDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTHANDH", DbType="NVarChar(255)")]
		public string SOTHANDH
		{
			get
			{
				return this._SOTHANDH;
			}
			set
			{
				if ((this._SOTHANDH != value))
				{
					this.OnSOTHANDHChanging(value);
					this.SendPropertyChanging();
					this._SOTHANDH = value;
					this.SendPropertyChanged("SOTHANDH");
					this.OnSOTHANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="NVarChar(255)")]
		public string CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITHAN", DbType="NVarChar(255)")]
		public string CHITHAN
		{
			get
			{
				return this._CHITHAN;
			}
			set
			{
				if ((this._CHITHAN != value))
				{
					this.OnCHITHANChanging(value);
					this.SendPropertyChanging();
					this._CHITHAN = value;
					this.SendPropertyChanged("CHITHAN");
					this.OnCHITHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIGOC", DbType="NVarChar(255)")]
		public string CHIGOC
		{
			get
			{
				return this._CHIGOC;
			}
			set
			{
				if ((this._CHIGOC != value))
				{
					this.OnCHIGOCChanging(value);
					this.SendPropertyChanging();
					this._CHIGOC = value;
					this.SendPropertyChanged("CHIGOC");
					this.OnCHIGOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRIDHN", DbType="NVarChar(255)")]
		public string VITRIDHN
		{
			get
			{
				return this._VITRIDHN;
			}
			set
			{
				if ((this._VITRIDHN != value))
				{
					this.OnVITRIDHNChanging(value);
					this.SendPropertyChanging();
					this._VITRIDHN = value;
					this.SendPropertyChanged("VITRIDHN");
					this.OnVITRIDHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODHN", DbType="NVarChar(255)")]
		public string SODHN
		{
			get
			{
				return this._SODHN;
			}
			set
			{
				if ((this._SODHN != value))
				{
					this.OnSODHNChanging(value);
					this.SendPropertyChanging();
					this._SODHN = value;
					this.SendPropertyChanged("SODHN");
					this.OnSODHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHAY", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHAY
		{
			get
			{
				return this._NGAYTHAY;
			}
			set
			{
				if ((this._NGAYTHAY != value))
				{
					this.OnNGAYTHAYChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHAY = value;
					this.SendPropertyChanged("NGAYTHAY");
					this.OnNGAYTHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKIEMDINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYKIEMDINH
		{
			get
			{
				return this._NGAYKIEMDINH;
			}
			set
			{
				if ((this._NGAYKIEMDINH != value))
				{
					this.OnNGAYKIEMDINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYKIEMDINH = value;
					this.SendPropertyChanged("NGAYKIEMDINH");
					this.OnNGAYKIEMDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSTHUE", DbType="NVarChar(255)")]
		public string MSTHUE
		{
			get
			{
				return this._MSTHUE;
			}
			set
			{
				if ((this._MSTHUE != value))
				{
					this.OnMSTHUEChanging(value);
					this.SendPropertyChanging();
					this._MSTHUE = value;
					this.SendPropertyChanged("MSTHUE");
					this.OnMSTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHO", DbType="NVarChar(255)")]
		public string SOHO
		{
			get
			{
				return this._SOHO;
			}
			set
			{
				if ((this._SOHO != value))
				{
					this.OnSOHOChanging(value);
					this.SendPropertyChanging();
					this._SOHO = value;
					this.SendPropertyChanged("SOHO");
					this.OnSOHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOKYTRUOC", DbType="NVarChar(255)")]
		public string CHISOKYTRUOC
		{
			get
			{
				return this._CHISOKYTRUOC;
			}
			set
			{
				if ((this._CHISOKYTRUOC != value))
				{
					this.OnCHISOKYTRUOCChanging(value);
					this.SendPropertyChanging();
					this._CHISOKYTRUOC = value;
					this.SendPropertyChanged("CHISOKYTRUOC");
					this.OnCHISOKYTRUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAOTHAY", DbType="Bit")]
		public System.Nullable<bool> BAOTHAY
		{
			get
			{
				return this._BAOTHAY;
			}
			set
			{
				if ((this._BAOTHAY != value))
				{
					this.OnBAOTHAYChanging(value);
					this.SendPropertyChanging();
					this._BAOTHAY = value;
					this.SendPropertyChanged("BAOTHAY");
					this.OnBAOTHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="NVarChar(100)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this.OnMODIFYDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFYDATE = value;
					this.SendPropertyChanged("MODIFYDATE");
					this.OnMODIFYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYBY", DbType="NVarChar(100)")]
		public string MODIFYBY
		{
			get
			{
				return this._MODIFYBY;
			}
			set
			{
				if ((this._MODIFYBY != value))
				{
					this.OnMODIFYBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFYBY = value;
					this.SendPropertyChanged("MODIFYBY");
					this.OnMODIFYBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KY", DbType="Int")]
		public System.Nullable<int> KY
		{
			get
			{
				return this._KY;
			}
			set
			{
				if ((this._KY != value))
				{
					this.OnKYChanging(value);
					this.SendPropertyChanging();
					this._KY = value;
					this.SendPropertyChanged("KY");
					this.OnKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Int")]
		public System.Nullable<int> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this.OnNAMChanging(value);
					this.SendPropertyChanging();
					this._NAM = value;
					this.SendPropertyChanged("NAM");
					this.OnNAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(100)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KY_", DbType="Int")]
		public System.Nullable<int> KY_
		{
			get
			{
				return this._KY_;
			}
			set
			{
				if ((this._KY_ != value))
				{
					this.OnKY_Changing(value);
					this.SendPropertyChanging();
					this._KY_ = value;
					this.SendPropertyChanged("KY_");
					this.OnKY_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMA", DbType="VarChar(255)")]
		public string MADMA
		{
			get
			{
				return this._MADMA;
			}
			set
			{
				if ((this._MADMA != value))
				{
					this.OnMADMAChanging(value);
					this.SendPropertyChanging();
					this._MADMA = value;
					this.SendPropertyChanged("MADMA");
					this.OnMADMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKYDS", DbType="Int")]
		public System.Nullable<int> CHUKYDS
		{
			get
			{
				return this._CHUKYDS;
			}
			set
			{
				if ((this._CHUKYDS != value))
				{
					this.OnCHUKYDSChanging(value);
					this.SendPropertyChanging();
					this._CHUKYDS = value;
					this.SendPropertyChanged("CHUKYDS");
					this.OnCHUKYDSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_GANMOI")]
	public partial class TB_GANMOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SHS;
		
		private string _DANHBO;
		
		private string _HOPDONG;
		
		private string _HOTEN;
		
		private string _SONHA;
		
		private string _DUONG;
		
		private string _MAPHUONG;
		
		private string _MAQUAN;
		
		private string _PLT;
		
		private string _GIABIEU;
		
		private string _DINHMUC;
		
		private string _HIEULUC;
		
		private System.Nullable<System.DateTime> _NGAYGANTLK;
		
		private string _HIEU;
		
		private string _COTLK;
		
		private string _SOTLK;
		
		private string _CHISOTLK;
		
		private string _SOHO;
		
		private string _TODS;
		
		private string _DOT;
		
		private string _MAYDS;
		
		private System.Nullable<bool> _CHUYEN;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYBY;
		
		private string _BANGKE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSHSChanging(string value);
    partial void OnSHSChanged();
    partial void OnDANHBOChanging(string value);
    partial void OnDANHBOChanged();
    partial void OnHOPDONGChanging(string value);
    partial void OnHOPDONGChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSONHAChanging(string value);
    partial void OnSONHAChanged();
    partial void OnDUONGChanging(string value);
    partial void OnDUONGChanged();
    partial void OnMAPHUONGChanging(string value);
    partial void OnMAPHUONGChanged();
    partial void OnMAQUANChanging(string value);
    partial void OnMAQUANChanged();
    partial void OnPLTChanging(string value);
    partial void OnPLTChanged();
    partial void OnGIABIEUChanging(string value);
    partial void OnGIABIEUChanged();
    partial void OnDINHMUCChanging(string value);
    partial void OnDINHMUCChanged();
    partial void OnHIEULUCChanging(string value);
    partial void OnHIEULUCChanged();
    partial void OnNGAYGANTLKChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGANTLKChanged();
    partial void OnHIEUChanging(string value);
    partial void OnHIEUChanged();
    partial void OnCOTLKChanging(string value);
    partial void OnCOTLKChanged();
    partial void OnSOTLKChanging(string value);
    partial void OnSOTLKChanged();
    partial void OnCHISOTLKChanging(string value);
    partial void OnCHISOTLKChanged();
    partial void OnSOHOChanging(string value);
    partial void OnSOHOChanged();
    partial void OnTODSChanging(string value);
    partial void OnTODSChanged();
    partial void OnDOTChanging(string value);
    partial void OnDOTChanged();
    partial void OnMAYDSChanging(string value);
    partial void OnMAYDSChanged();
    partial void OnCHUYENChanging(System.Nullable<bool> value);
    partial void OnCHUYENChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnMODIFYDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFYDATEChanged();
    partial void OnMODIFYBYChanging(string value);
    partial void OnMODIFYBYChanged();
    partial void OnBANGKEChanging(string value);
    partial void OnBANGKEChanged();
    #endregion
		
		public TB_GANMOI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHS", DbType="NVarChar(50)")]
		public string SHS
		{
			get
			{
				return this._SHS;
			}
			set
			{
				if ((this._SHS != value))
				{
					this.OnSHSChanging(value);
					this.SendPropertyChanging();
					this._SHS = value;
					this.SendPropertyChanged("SHS");
					this.OnSHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DANHBO
		{
			get
			{
				return this._DANHBO;
			}
			set
			{
				if ((this._DANHBO != value))
				{
					this.OnDANHBOChanging(value);
					this.SendPropertyChanging();
					this._DANHBO = value;
					this.SendPropertyChanged("DANHBO");
					this.OnDANHBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOPDONG", DbType="NVarChar(50)")]
		public string HOPDONG
		{
			get
			{
				return this._HOPDONG;
			}
			set
			{
				if ((this._HOPDONG != value))
				{
					this.OnHOPDONGChanging(value);
					this.SendPropertyChanging();
					this._HOPDONG = value;
					this.SendPropertyChanged("HOPDONG");
					this.OnHOPDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(MAX)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONHA", DbType="NVarChar(MAX)")]
		public string SONHA
		{
			get
			{
				return this._SONHA;
			}
			set
			{
				if ((this._SONHA != value))
				{
					this.OnSONHAChanging(value);
					this.SendPropertyChanging();
					this._SONHA = value;
					this.SendPropertyChanged("SONHA");
					this.OnSONHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUONG", DbType="NVarChar(MAX)")]
		public string DUONG
		{
			get
			{
				return this._DUONG;
			}
			set
			{
				if ((this._DUONG != value))
				{
					this.OnDUONGChanging(value);
					this.SendPropertyChanging();
					this._DUONG = value;
					this.SendPropertyChanged("DUONG");
					this.OnDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHUONG", DbType="NVarChar(20)")]
		public string MAPHUONG
		{
			get
			{
				return this._MAPHUONG;
			}
			set
			{
				if ((this._MAPHUONG != value))
				{
					this.OnMAPHUONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHUONG = value;
					this.SendPropertyChanged("MAPHUONG");
					this.OnMAPHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQUAN", DbType="NVarChar(20)")]
		public string MAQUAN
		{
			get
			{
				return this._MAQUAN;
			}
			set
			{
				if ((this._MAQUAN != value))
				{
					this.OnMAQUANChanging(value);
					this.SendPropertyChanging();
					this._MAQUAN = value;
					this.SendPropertyChanged("MAQUAN");
					this.OnMAQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLT", DbType="NVarChar(50)")]
		public string PLT
		{
			get
			{
				return this._PLT;
			}
			set
			{
				if ((this._PLT != value))
				{
					this.OnPLTChanging(value);
					this.SendPropertyChanging();
					this._PLT = value;
					this.SendPropertyChanged("PLT");
					this.OnPLTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABIEU", DbType="NVarChar(50)")]
		public string GIABIEU
		{
			get
			{
				return this._GIABIEU;
			}
			set
			{
				if ((this._GIABIEU != value))
				{
					this.OnGIABIEUChanging(value);
					this.SendPropertyChanging();
					this._GIABIEU = value;
					this.SendPropertyChanged("GIABIEU");
					this.OnGIABIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DINHMUC", DbType="NVarChar(10)")]
		public string DINHMUC
		{
			get
			{
				return this._DINHMUC;
			}
			set
			{
				if ((this._DINHMUC != value))
				{
					this.OnDINHMUCChanging(value);
					this.SendPropertyChanging();
					this._DINHMUC = value;
					this.SendPropertyChanged("DINHMUC");
					this.OnDINHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="NVarChar(10)")]
		public string HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this.OnHIEULUCChanging(value);
					this.SendPropertyChanging();
					this._HIEULUC = value;
					this.SendPropertyChanged("HIEULUC");
					this.OnHIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGANTLK", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGANTLK
		{
			get
			{
				return this._NGAYGANTLK;
			}
			set
			{
				if ((this._NGAYGANTLK != value))
				{
					this.OnNGAYGANTLKChanging(value);
					this.SendPropertyChanging();
					this._NGAYGANTLK = value;
					this.SendPropertyChanged("NGAYGANTLK");
					this.OnNGAYGANTLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEU", DbType="NVarChar(100)")]
		public string HIEU
		{
			get
			{
				return this._HIEU;
			}
			set
			{
				if ((this._HIEU != value))
				{
					this.OnHIEUChanging(value);
					this.SendPropertyChanging();
					this._HIEU = value;
					this.SendPropertyChanged("HIEU");
					this.OnHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTLK", DbType="NVarChar(100)")]
		public string COTLK
		{
			get
			{
				return this._COTLK;
			}
			set
			{
				if ((this._COTLK != value))
				{
					this.OnCOTLKChanging(value);
					this.SendPropertyChanging();
					this._COTLK = value;
					this.SendPropertyChanged("COTLK");
					this.OnCOTLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTLK", DbType="NVarChar(100)")]
		public string SOTLK
		{
			get
			{
				return this._SOTLK;
			}
			set
			{
				if ((this._SOTLK != value))
				{
					this.OnSOTLKChanging(value);
					this.SendPropertyChanging();
					this._SOTLK = value;
					this.SendPropertyChanged("SOTLK");
					this.OnSOTLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOTLK", DbType="NVarChar(100)")]
		public string CHISOTLK
		{
			get
			{
				return this._CHISOTLK;
			}
			set
			{
				if ((this._CHISOTLK != value))
				{
					this.OnCHISOTLKChanging(value);
					this.SendPropertyChanging();
					this._CHISOTLK = value;
					this.SendPropertyChanged("CHISOTLK");
					this.OnCHISOTLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHO", DbType="NVarChar(100)")]
		public string SOHO
		{
			get
			{
				return this._SOHO;
			}
			set
			{
				if ((this._SOHO != value))
				{
					this.OnSOHOChanging(value);
					this.SendPropertyChanging();
					this._SOHO = value;
					this.SendPropertyChanged("SOHO");
					this.OnSOHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TODS", DbType="NVarChar(100)")]
		public string TODS
		{
			get
			{
				return this._TODS;
			}
			set
			{
				if ((this._TODS != value))
				{
					this.OnTODSChanging(value);
					this.SendPropertyChanging();
					this._TODS = value;
					this.SendPropertyChanged("TODS");
					this.OnTODSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOT", DbType="NVarChar(100)")]
		public string DOT
		{
			get
			{
				return this._DOT;
			}
			set
			{
				if ((this._DOT != value))
				{
					this.OnDOTChanging(value);
					this.SendPropertyChanging();
					this._DOT = value;
					this.SendPropertyChanged("DOT");
					this.OnDOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAYDS", DbType="NVarChar(100)")]
		public string MAYDS
		{
			get
			{
				return this._MAYDS;
			}
			set
			{
				if ((this._MAYDS != value))
				{
					this.OnMAYDSChanging(value);
					this.SendPropertyChanging();
					this._MAYDS = value;
					this.SendPropertyChanged("MAYDS");
					this.OnMAYDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUYEN", DbType="Bit")]
		public System.Nullable<bool> CHUYEN
		{
			get
			{
				return this._CHUYEN;
			}
			set
			{
				if ((this._CHUYEN != value))
				{
					this.OnCHUYENChanging(value);
					this.SendPropertyChanging();
					this._CHUYEN = value;
					this.SendPropertyChanged("CHUYEN");
					this.OnCHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="NVarChar(100)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this.OnMODIFYDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFYDATE = value;
					this.SendPropertyChanged("MODIFYDATE");
					this.OnMODIFYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYBY", DbType="NVarChar(100)")]
		public string MODIFYBY
		{
			get
			{
				return this._MODIFYBY;
			}
			set
			{
				if ((this._MODIFYBY != value))
				{
					this.OnMODIFYBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFYBY = value;
					this.SendPropertyChanged("MODIFYBY");
					this.OnMODIFYBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANGKE", DbType="NVarChar(MAX)")]
		public string BANGKE
		{
			get
			{
				return this._BANGKE;
			}
			set
			{
				if ((this._BANGKE != value))
				{
					this.OnBANGKEChanging(value);
					this.SendPropertyChanging();
					this._BANGKE = value;
					this.SendPropertyChanged("BANGKE");
					this.OnBANGKEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
