DROP TABLE KTTC_HESOQUYETTOAN
GO

CREATE TABLE KTTC_HESOQUYETTOAN
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NHANCONG FLOAT,
	MAYTC FLOAT,
	CHIPHICUNG FLOAT,
	TNCHUITHUE FLOAT,
	THUE FLOAT,
	MODIFYBY NVARCHAR(250),
	MODIFYDATE DATETIME
)
GO

INSERT INTO KTTC_HESOQUYETTOAN(NHANCONG,MAYTC,CHIPHICUNG,TNCHUITHUE,THUE,MODIFYBY,MODIFYDATE)
VALUES('2.8','1.34','0.05','0.055','0.1','sys','02/27/2012')
GO

DROP TABLE KTTC_QUYETTOAN_GANDHN 
GO

CREATE TABLE KTTC_QUYETTOAN_GANDHN
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	STT INT,
	DOTQT VARCHAR(50),
	NHATHAU NVARCHAR(MAX),
	TONGSODHN INT,
	QUYETTOAN DATETIME,
	THANHTOAN DATETIME,
	SOHOSO VARCHAR(50),
	TENKH NVARCHAR(MAX),
	SONHA NVARCHAR(MAX),
	TENDUONG NVARCHAR(MAX),
	PHUONG NVARCHAR(MAX),
	QUAN NVARCHAR(MAX),
	SODHN INT,
	CATDA FLOAT,
	NHANCONG FLOAT,
	CPNC FLOAT,
	CP_NHANCONG FLOAT,
	MAYTC FLOAT,
	MAYTHICONG FLOAT,
	CP_MAYTC FLOAT,
	CHIPHICHUNG FLOAT,
	CP_CHUNG FLOAT,
	THUNHAPCHUITHUE FLOAT,
	CP_TNCTTT FLOAT,
	GXLTT FLOAT,
	THUE FLOAT,
	SAUTHUE FLOAT,
	GHICHU NVARCHAR(MAX),
	CREATEBY NVARCHAR(250),
	CREATEDATE DATETIME
)
GO

DROP VIEW KTTC_HOSOKHACHHANG
GO

CREATE VIEW KTTC_HOSOKHACHHANG
AS
	SELECT kh.MADOT, kh.SOHOSO, kh.SHS, DANHBO,HOPDONG,UPPER(HOTEN) AS 'HOTEN',DIENTHOAI,SOHO,UPPER( SONHA) AS 'SONHA',UPPER(DUONG) AS 'DUONG', p.MAPHUONG, UPPER(p.TENPHUONG ) AS 'TENPHUONG'  ,q.MAQUAN,  UPPER(q.TENQUAN) AS 'TENQUAN' 
	FROM    DON_KHACHHANG kh,QUAN q,PHUONG p 
	WHERE  kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG 
GO

SELECT STT, DOTQT, NHATHAU, TONGSODHN, QUYETTOAN, THANHTOAN, SOHOSO, TENKH, SONHA, TENDUONG, PHUONG, QUAN
		, SODHN,CONVERT(varchar(50),CATDA) as 'CATDA', NHANCONG, CPNC, CP_NHANCONG,CONVERT(varchar(50),MAYTC) as 'MAYTC' , MAYTHICONG, CP_MAYTC,convert(varchar,convert(decimal(20,2), CHIPHICHUNG)) , CP_CHUNG
		, THUNHAPCHUITHUE, CP_TNCTTT, GXLTT, THUE, SAUTHUE, GHICHU
FROM KTTC_QUYETTOAN_GANDHN 
WHERE DOTQT =''
ORDER BY STT DESC